# Generated by Django 3.2.6 on 2021-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_video_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='media.Tag'),
        ),
    ]
