# Generated by Django 3.2.6 on 2021-08-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
