# Generated by Django 3.2.6 on 2021-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordervideo',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
