# Generated by Django 3.2.6 on 2021-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
