# Generated by Django 3.2.6 on 2021-08-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20210826_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
