# Generated by Django 3.2.6 on 2021-08-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_auto_20210826_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderVideo',
            new_name='OrderItem',
        ),
    ]
