# Generated by Django 3.2.6 on 2021-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_rename_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
