# Generated by Django 3.2.6 on 2021-08-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_video_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
